name: CI

on: [push, pull_request]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the website
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install wheel
          pip install -r requirements.txt
          python3 -m pelican --fatal warnings -s publishconf.py
